// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/view-all-events/CardGrid.tsx": () => import("../components/mockups/view-all-events/CardGrid.tsx"),
  "./components/mockups/view-all-events/Editorial.tsx": () => import("../components/mockups/view-all-events/Editorial.tsx")
};
