// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/two-level-filter/FilterActive.tsx": () => import("../components/mockups/two-level-filter/FilterActive.tsx"),
  "./components/mockups/two-level-filter/FilterDefault.tsx": () => import("../components/mockups/two-level-filter/FilterDefault.tsx"),
  "./components/mockups/view-all-events/CardGrid.tsx": () => import("../components/mockups/view-all-events/CardGrid.tsx"),
  "./components/mockups/view-all-events/Editorial.tsx": () => import("../components/mockups/view-all-events/Editorial.tsx")
};
